# Generated by Django 3.2.13 on 2022-05-31 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220515_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='base_currency',
        ),
    ]
