# Generated by Django 3.2.13 on 2022-05-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20220515_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparisondetails',
            old_name='amount',
            new_name='value',
        ),
    ]
