# Generated by Django 3.2.13 on 2022-05-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_rename_amount_comparisondetails_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparisondetails',
            old_name='value',
            new_name='bye_value',
        ),
        migrations.AddField(
            model_name='comparisondetails',
            name='profit_margin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
