# Generated by Django 3.2.13 on 2022-05-17 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_auto_20220516_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisondetails',
            name='comparison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_details', to='currency.comparison'),
        ),
        migrations.AlterField(
            model_name='comparisondetails',
            name='normal_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_details', to='currency.currency'),
        ),
    ]
