# Generated by Django 3.2.13 on 2022-05-31 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_auto_20220517_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='comparisondetails',
            name='close_Price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comparisondetails',
            name='open_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currency',
            name='close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='open_time',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='DayValuesLowHigh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_value', models.FloatField()),
                ('high_value', models.FloatField()),
                ('day_values', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_values_low_high', to='currency.dayvalues')),
                ('normal_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_values_low_high', to='currency.currency')),
            ],
        ),
        migrations.AddField(
            model_name='dayvalues',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_values_bases', to='currency.currency'),
        ),
        migrations.AddField(
            model_name='dayvalues',
            name='normal_currencies',
            field=models.ManyToManyField(related_name='day_values', through='currency.DayValuesLowHigh', to='currency.Currency'),
        ),
    ]
