# Generated by Django 3.2.13 on 2022-05-31 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_auto_20220531_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='open_time',
        ),
    ]
