# Generated by Django 3.2.13 on 2022-05-31 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_auto_20220531_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='close_time',
            field=models.TimeField(default=datetime.time(5, 30)),
        ),
        migrations.AddField(
            model_name='currency',
            name='open_time',
            field=models.TimeField(default=datetime.time(1, 15)),
        ),
    ]
