# Generated by Django 3.2.13 on 2022-05-31 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_auto_20220531_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comparisondetails',
            old_name='close_Price',
            new_name='close_price',
        ),
    ]
