# Generated by Django 3.2.13 on 2022-06-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_rename_close_price_comparisondetails_close_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='open_time',
        ),
    ]
