# Generated by Django 3.2.13 on 2022-06-01 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0012_auto_20220601_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='close_time',
            field=models.TimeField(default=datetime.time(18, 30)),
        ),
        migrations.AddField(
            model_name='currency',
            name='open_time',
            field=models.TimeField(default=datetime.time(13, 15)),
        ),
    ]
