# Generated by Django 3.2.13 on 2022-06-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0013_auto_20220601_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='open_time',
        ),
    ]
