# Generated by Django 3.2.13 on 2022-06-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0015_auto_20220601_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='currencies',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comparisondetails',
            name='profit_margin',
        ),
        migrations.AddField(
            model_name='currency',
            name='profit_margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CurrencyDetails',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
