# Generated by Django 3.2.13 on 2022-06-02 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0016_auto_20220601_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitMargin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='currency',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='open_time',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='profit_margin',
        ),
        migrations.AlterField(
            model_name='dayvalues',
            name='normal_currencies',
            field=models.ManyToManyField(through='currency.DayValuesLowHigh', to='currency.Currency'),
        ),
        migrations.CreateModel(
            name='ProfitMarginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('normal_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_margin_details', to='currency.currency')),
                ('profit_margin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_margin_details', to='currency.profitmargin')),
            ],
        ),
        migrations.AddField(
            model_name='profitmargin',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_margin_bases', to='currency.currency'),
        ),
        migrations.AddField(
            model_name='profitmargin',
            name='normal_currencies',
            field=models.ManyToManyField(through='currency.ProfitMarginDetails', to='currency.Currency'),
        ),
    ]
