# Generated by Django 3.2.13 on 2022-06-02 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0017_auto_20220602_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='close_time',
            field=models.TimeField(default=datetime.time(10, 30)),
        ),
        migrations.AddField(
            model_name='currency',
            name='open_time',
            field=models.TimeField(default=datetime.time(3, 10)),
        ),
    ]
