# Generated by Django 4.0.5 on 2022-06-05 17:24

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0018_auto_20220602_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='body1',
        ),
        migrations.AddField(
            model_name='currency',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='header',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.TextField(blank=True, null=True)),
                ('p2', models.TextField(blank=True, null=True)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paraghraphs', to='currency.currency')),
            ],
        ),
        migrations.CreateModel(
            name='NewsAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=100)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='currency.assetstype')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='paragraphs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='currency.paragraph'),
        ),
    ]
