# Generated by Django 4.0.5 on 2022-06-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0021_currency_close_time_currency_open_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='open_time',
        ),
    ]
