# Generated by Django 4.0.5 on 2022-06-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0023_currency_close_time_currency_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='header',
            field=models.TextField(),
        ),
    ]
