# Generated by Django 4.0.5 on 2022-06-06 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0024_alter_news_header'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='open_time',
        ),
    ]
