# Generated by Django 4.0.5 on 2022-06-06 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0025_remove_currency_close_time_remove_currency_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='close_time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AddField(
            model_name='currency',
            name='open_time',
            field=models.TimeField(default=datetime.time(0, 5)),
        ),
    ]
