# Generated by Django 4.0.5 on 2022-06-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0026_currency_close_time_currency_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sub_header',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profitmargin',
            name='base_currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_margin_bases', to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='profitmargindetails',
            name='normal_currency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_margin_details', to='currency.currency'),
        ),
    ]
