# Generated by Django 4.0.5 on 2022-06-06 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0027_news_sub_header_alter_profitmargin_base_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='currency.news'),
        ),
    ]
