# Generated by Django 4.0.5 on 2022-06-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0030_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='ar_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
